### ISSUE TITLE
What is the theme in the screenshot?

### ISSUE THREAD

**Issue by psyanite** [JonathanSpeek/palenight-iterm2#1]
Hi Jonathan, thank you so much for creating this, I would love to know what theme you are using in the screenshot, and any other bits of information on how I could replicate this.

Kind regards,

N

**Comment by JonathanSpeek** [comment]
@psyanite I'm using [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) with the [spaceship prompt](https://github.com/denysdovhan/spaceship-prompt)
